# Generated by Django 4.2 on 2023-05-03 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File',
        ),
    ]
